service: reuse-tests

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  func-under-test:
    handler: functions/get.handler
    events:
      - http:
          path: /
          method: get